---
- name: Prepare
  hosts: all
  tasks:
    - name: "Create group consul"
      ansible.builtin.group:
        name: "consul"
        state: present
      become: true

    - name: "Create user consul"
      ansible.builtin.user:
        name: "consul"
        group: "consul"
        shell: /bin/false
        state: present
      become: true
