---
# handlers file for renew_consul_certificates
- name: "Reload service file"
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemctl-daemon-reload"

- name: "Enable consul-certs service"
  ansible.builtin.service:
    name: consul-certs
    enabled: true
  listen: "systemctl-enable-consul-certs"

- name: "Start consul-certs service"
  ansible.builtin.service:
    name: consul-certs
    state: restarted
  listen: "systemctl-restart-consul-certs"
  when: renew_consul_certificates_start_service
